// <auto-generated />
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Data.Migrations
{
    [DbContext(typeof(GeographicalDataContext))]
    [Migration("20250722192145_ModelCleanup")]
    partial class ModelCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BE.Domain.Entities.GeographicalDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("gemeente");

                    b.Property<string>("Huisletter")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("huisletter");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("huisnummer");

                    b.Property<int?>("Huisnummertoevoeging")
                        .HasColumnType("INTEGER")
                        .HasColumnName("huisnummertoevoeging");

                    b.Property<double>("Lat")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lon");

                    b.Property<string>("Nevenadres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nevenadres");

                    b.Property<string>("Nummeraanduiding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nummeraanduiding");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("objectid");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("objecttype");

                    b.Property<string>("Openbareruimte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("openbareruimte");

                    b.Property<int>("Oppervlakteverblijfsobject")
                        .HasColumnType("INTEGER")
                        .HasColumnName("oppervlakteverblijfsobject");

                    b.Property<int>("Pandbouwjaar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pandbouwjaar");

                    b.Property<string>("Pandid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("pandid");

                    b.Property<string>("Pandstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("pandstatus");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("postcode");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("provincie");

                    b.Property<string>("Verblijfsobjectgebruiksdoel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("verblijfsobjectgebruiksdoel");

                    b.Property<string>("Verblijfsobjectstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("verblijfsobjectstatus");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("woonplaats");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("Gemeente")
                        .HasDatabaseName("IX_GeographicalData_Gemeente");

                    b.HasIndex("Postcode")
                        .HasDatabaseName("IX_GeographicalData_Postcode");

                    b.HasIndex("Woonplaats")
                        .HasDatabaseName("IX_GeographicalData_Woonplaats");

                    b.HasIndex("Openbareruimte", "Huisnummer", "Postcode")
                        .HasDatabaseName("IX_GeographicalData_Address");

                    b.ToTable("GeographicalData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
